name: Update ref

on:
  repository_dispatch:
    types: [trigger-update-ref]

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodules
        run: git submodule update --remote
      
      - name: Commit and push changes
        run: |
            git add .
            git commit -m "bot(feat): update submodules"
            git push
